const $=(s)=>document.querySelector(s); let token=sessionStorage.getItem("sessionToken")||""; let currentUser=null; let expenseCache=[];
function msg(el,text,isError=false){el.textContent=text;el.classList.toggle("error",isError)}
async function api(path,options={}){const headers={"Content-Type":"application/json",...(options.headers||{})};if(token)headers.Authorization=`Bearer ${token}`;const response=await fetch(path,{...options,headers});let data={};try{data=await response.json()}catch{}if(!response.ok)throw new Error(data.errors?.join(" ")||data.message||`Request failed (${response.status}).`);return data}
function esc(v){return String(v??"").replace(/[&<>'"]/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;","'":"&#39;",'"':"&quot;"}[c]))}
function nowMonth(){return new Date().toISOString().slice(0,7)}
async function init(){try{const h=await api("/api/health");$("#healthStatus").textContent=`Server: ${h.status} | ${h.database}`;}catch{$("#healthStatus").textContent="Server unavailable"}$("#budgetMonth").value=nowMonth();$("#reportMonth").value=nowMonth();if(token){try{currentUser=(await api("/api/auth/me")).user}catch{token="";sessionStorage.removeItem("sessionToken")}}await renderSession()}
async function renderSession(){document.querySelectorAll(".app-only").forEach(e=>e.style.display=currentUser?"block":"none");document.querySelectorAll(".admin-only").forEach(e=>e.style.display=currentUser?.role==="admin"?"block":"none");$("#currentUser").textContent=currentUser?`Logged in as ${currentUser.name} (${currentUser.email}, ${currentUser.role})`:"No user logged in.";if(currentUser){await loadExpenses();await loadBudgetStatus();if(currentUser.role==="admin")await loadUsers()}}
async function loadExpenses(){const category=$("#categoryFilter").value;expenseCache=(await api(`/api/expenses${category?`?category=${encodeURIComponent(category)}`:""}`)).expenses;$("#expenseTableBody").innerHTML=expenseCache.map(e=>`<tr><td>${esc(e.title)}</td><td>${e.amount.toFixed(2)}</td><td>${esc(e.category)}</td><td>${esc(e.date)}</td><td><button class="small" data-edit="${e.expenseId}">Edit</button> <button class="small danger" data-delete="${e.expenseId}">Delete</button></td></tr>`).join("")||`<tr><td colspan="5">No expense records.</td></tr>`}
async function loadBudgetStatus(){const month=$("#budgetMonth").value||nowMonth();try{const s=(await api(`/api/budget/status?month=${month}`)).status;msg($("#budgetStatus"),`${s.message} Spent ${s.spent.toFixed(2)} / ${s.limit.toFixed(2)}; remaining ${s.remaining.toFixed(2)}.`)}catch(e){msg($("#budgetStatus"),e.message,true)}}
async function loadUsers(){const users=(await api("/api/admin/users")).users;$("#userTableBody").innerHTML=users.map(u=>`<tr data-user="${u.userId}"><td>${esc(u.name)}</td><td>${esc(u.email)}</td><td><select data-role><option ${u.role==="user"?"selected":""}>user</option><option ${u.role==="admin"?"selected":""}>admin</option></select></td><td><select data-status><option ${u.status==="active"?"selected":""}>active</option><option ${u.status==="disabled"?"selected":""}>disabled</option></select></td><td>${u.userId===currentUser.userId?"Current account":`<button class="small" data-save-user>Save</button> <button class="small danger" data-delete-user>Delete</button>`}</td></tr>`).join("")}
$("#registerForm").addEventListener("submit",async e=>{e.preventDefault();try{await api("/api/auth/register",{method:"POST",body:JSON.stringify({name:$("#registerName").value,email:$("#registerEmail").value,password:$("#registerPassword").value})});e.target.reset();msg($("#registerMessage"),"Registration successful. You can now log in.")}catch(err){msg($("#registerMessage"),err.message,true)}})
$("#loginForm").addEventListener("submit",async e=>{e.preventDefault();try{const r=await api("/api/auth/login",{method:"POST",body:JSON.stringify({email:$("#loginEmail").value,password:$("#loginPassword").value})});token=r.token;sessionStorage.setItem("sessionToken",token);currentUser=r.user;e.target.reset();msg($("#loginMessage"),"Login successful.");await renderSession()}catch(err){msg($("#loginMessage"),err.message,true)}})
$("#logoutBtn").addEventListener("click",async()=>{try{if(token)await api("/api/auth/logout",{method:"POST"})}catch{}token="";currentUser=null;sessionStorage.removeItem("sessionToken");await renderSession()})
function resetExpense(){ $("#expenseForm").reset();$("#expenseId").value="";$("#submitExpenseBtn").textContent="Add Expense" }
$("#expenseForm").addEventListener("submit",async e=>{e.preventDefault();const id=$("#expenseId").value;const payload={title:$("#title").value,amount:$("#amount").value,category:$("#category").value,date:$("#date").value};try{await api(id?`/api/expenses/${id}`:"/api/expenses",{method:id?"PUT":"POST",body:JSON.stringify(payload)});msg($("#expenseMessage"),id?"Expense updated successfully.":"Expense added successfully.");resetExpense();await loadExpenses();await loadBudgetStatus()}catch(err){msg($("#expenseMessage"),err.message,true)}})
$("#cancelEditBtn").addEventListener("click",resetExpense)
$("#expenseTableBody").addEventListener("click",async e=>{const edit=e.target.dataset.edit,del=e.target.dataset.delete;if(edit){const x=expenseCache.find(v=>v.expenseId===Number(edit));$("#expenseId").value=x.expenseId;$("#title").value=x.title;$("#amount").value=x.amount;$("#category").value=x.category;$("#date").value=x.date;$("#submitExpenseBtn").textContent="Update Expense"}if(del&&confirm("Delete this expense?")){try{await api(`/api/expenses/${del}`,{method:"DELETE"});await loadExpenses();await loadBudgetStatus();msg($("#expenseMessage"),"Expense deleted successfully.")}catch(err){msg($("#expenseMessage"),err.message,true)}}})
$("#categoryFilter").addEventListener("change",loadExpenses)
$("#budgetMonth").addEventListener("change",loadBudgetStatus)
$("#setBudgetBtn").addEventListener("click",async()=>{try{await api("/api/budget",{method:"PUT",body:JSON.stringify({month:$("#budgetMonth").value,limit:$("#budgetLimit").value})});await loadBudgetStatus()}catch(err){msg($("#budgetStatus"),err.message,true)}})
$("#generateReportBtn").addEventListener("click",async()=>{try{$("#reportOutput").textContent=JSON.stringify((await api(`/api/reports/monthly?month=${$("#reportMonth").value}`)).report,null,2)}catch(err){$("#reportOutput").textContent=err.message}})
$("#analyzeTrendBtn").addEventListener("click",async()=>{try{$("#reportOutput").textContent=JSON.stringify(await api("/api/reports/trend"),null,2)}catch(err){$("#reportOutput").textContent=err.message}})
$("#refreshUsersBtn").addEventListener("click",loadUsers)
$("#userTableBody").addEventListener("click",async e=>{const row=e.target.closest("tr[data-user]");if(!row)return;const id=row.dataset.user;try{if(e.target.hasAttribute("data-save-user")){await api(`/api/admin/users/${id}`,{method:"PATCH",body:JSON.stringify({role:row.querySelector("[data-role]").value,status:row.querySelector("[data-status]").value})});msg($("#adminMessage"),"User account updated.");await loadUsers()}if(e.target.hasAttribute("data-delete-user")&&confirm("Permanently delete this user and their data?")){await api(`/api/admin/users/${id}`,{method:"DELETE"});msg($("#adminMessage"),"User account deleted.");await loadUsers()}}catch(err){msg($("#adminMessage"),err.message,true)}})
$("#feedbackForm").addEventListener("submit",async e=>{e.preventDefault();try{await api("/api/feedback",{method:"POST",body:JSON.stringify({iteration:Number($("#feedbackIteration").value),reviewer:$("#feedbackReviewer").value,outcome:$("#feedbackOutcome").value,comments:$("#feedbackComments").value})});e.target.reset();msg($("#feedbackMessage"),"Acceptance feedback saved to the database.")}catch(err){msg($("#feedbackMessage"),err.message,true)}})
init();
